spring:
  application:
    name: spring-ai-rag
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
server:
  port: 7001
sfg:
  aiapp:
    vectorStorePath: D:\\TEMP\\vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv